# Generated by Django 4.2.6 on 2023-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('StudentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Courses', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
