# Generated by Django 4.2.6 on 2023-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttenInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=50)),
                ('StudentID', models.CharField(max_length=50)),
                ('StudentName', models.CharField(max_length=500)),
                ('CourseNo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AttenInfo',
            },
        ),
    ]
